### PR TITLE
Merging login branch to main

### LINKED ISSUE #2: Login Functionality FE
- [ ] Create the Page

### PR DESCRIPTION
**Pull request by kana140**
## Merging Login branch to main 

Resolves #2 

This PR does the following

- makes FE for signup, login and landing page
- modifies files to use inline styling

### CODE REVIEW

**Comment by mlu415** [comment]
Is there a reason we are using inline styling?

**Review by mlu415 — CHANGES_REQUESTED** [review]
Would definitely not recommend inline styling

**Comment by mlu415** [comment]
> Is there a reason we are using inline styling?
> 
> not using css is a sure fire way to lose marks on code quality

resolved in discord to use module.css

**Comment by AoMedium** [comment]
Pages look great! 

Sorry for the confusion on the styling, I reckon we could start using modular css and reference the classes like how @mlu415 did in #45. I'll do the same on my branch for #38 etc

**Review by mlu415 — APPROVED** [review]
nice

**Review by Bac0nEater — APPROVED** [review]
lgtm

**Pull request merged**
