### PR TITLE
18 create all schemas

### PR DESCRIPTION
**Pull request by Bac0nEater**
#18

### CODE REVIEW

**Comment by Bac0nEater** [comment]
Created a test page that you can add/set a document, and also get all the documents from DB

**Review by mlu415 — CHANGES_REQUESTED** [review]
how are we keeping track of the questions users have completed?

**Comment by mlu415** [comment]
should this be a documentreference[]? instead of singular?

**Review by mlu415 — APPROVED** [review]
nice nice

**Review by AoMedium — APPROVED** [review]
Looks good!

**Pull request merged**
